Add a systemcmd "userspace_init" to initialize px4 in protected build user side
Kernel side platform services are initialized via BOARDCTL at boot.

User side platform services need to be started separately, so start
them using a systemcmd in startup script

Signed-off-by: Jukka Laitinen <jukkax@ssrc.tii.ae>

diff --git a/ROMFS/px4fmu_common/init.d/rcS b/ROMFS/px4fmu_common/init.d/rcS
--- a/ROMFS/px4fmu_common/init.d/rcS
+++ b/ROMFS/px4fmu_common/init.d/rcS
@@ -67,6 +67,11 @@ sercon
 ver all
 
 #
+# Initialize userspace px4 services
+# in protected/kernel builds
+userspace_init
+
+#
 # Try to mount the microSD card.
 #
 # REBOOTWORK this needs to start after the flight control loop.
@@ -148,6 +153,12 @@ else
 	if mft query -q -k MTD -s MTD_CALDATA -v /fs/mtd_caldata
 	then
 		param load /fs/mtd_caldata
+	fi
+
+	kparam select $PARAM_FILE
+	if ! kparam import
+	then
+		echo "ERROR: kernel paramers load failed"
 	fi
 
 	param select $PARAM_FILE
